include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

Build:
  extends: .build
  variables:
    CI_PROJECT_DIR: app

Deploy Test:
  extends: .deployHidora
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  environment:
    name: Test
    url: "https://survey-ggt.hidora.com"
