include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

Build:
  extends: .build
  variables:
    CI_PROJECT_DIR: ./app
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
