include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

Build:
  extends: .build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"

Deploy Test:
  extends: .deployHidora
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: "$CI_COMMIT_TAG != /v.*$/"
  environment:
    name: Test
    url: "https://survey-ggt.hidora.com"

Deploy Prod:
  extends: .deployHidora
  rules:
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  environment:
    name: Prod
    url: "https://"
